spring.application.name=passwordvault

spring.datasource.url=jdbc:postgresql://localhost:5432/password_vault
spring.datasource.username=password_vault_user
spring.datasource.password=local_dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true